### ISSUE TITLE
Remove dependency on xo

### ISSUE THREAD

**Issue by appsforartists** [google/eslint-config-google#18]
[xo](https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js) is much more opinionated than [our Style Guide](https://google.github.io/styleguide/javascriptguide.xml).

I'm using this eslint config to write Google code, and I keep running into `xo`'s opinions on things that are either undefined or encouraged by our internal guide.  One of these days, I'm going to just read our internal guide and write a proper eslint config for it that doesn't inherit from anybody else's.  That gives us immunity, both now and as both configs evolve over time.

**Comment by appsforartists** [comment]
Consider adding comments to each rule that cite where it is in the guide/why that rule applies.

**Comment by dongbohu** [comment]
Seems that you have already removed the dependency on **xo**. Can you also update the npm module? Thanks.

**Comment by appsforartists** [comment]
Closed by #23.
