### ISSUE TITLE
Polymer({...}) generates new-cap error

### ISSUE THREAD

**Issue by dandv** [google/eslint-config-google#25]
Typical Polymer code such as

``` js
Polymer({
  is: 'my-view1',
  ...
});
```

generates the `A function with a name starting with an uppercase letter should only be used as a constructor. (new-cap)` error due to [`'new-cap': 2,`](https://github.com/google/eslint-config-google/blob/master/index.js#L220).

**Comment by stramel** [comment]
You could add this in your `globals` section

**Comment by philipwalton** [comment]
AFAIK, Polymer has its own JS style guide, so I don't think we need to make any exceptions here for Polymer. Polymer could create it's own eslint config that extends Google if it wants.
