### ISSUE TITLE
RFC: Add support for `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [google/eslint-config-google#34]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by philipwalton** [comment]
This is cool, but I'm not sure it belongs in this repo as Google's JS style doesn't have an opinion on when/how new browser APIs should be used.
