### ISSUE TITLE
ESLint failed: Cannot parse checkstyle XML in Webstorm

### ISSUE THREAD

**Issue by nickjuntilla** [google/eslint-config-google#35]
Trying to run .eslintrc.json with extends: "google" just like the readme says and I get the above error. When right clicking and trying to run eslint.

**Comment by nickjuntilla** [comment]
Got it working "extends" needs to be outside of "rules"

**Comment by liambowers** [comment]
I had this error and it turned out to be missing babel-eslint. A npm install -g babel-eslint sorted it.
