### ISSUE TITLE
show error using es6

### ISSUE THREAD

**Issue by freeliu** [google/eslint-config-google#38]
import $ from 'zepto'

Parsing error: The keyword 'import' is reserved

**Comment by philipwalton** [comment]
I'm not sure if this error is coming from eslint, but I believe in order to use modules you have to set up some config options like so:

```js
{
  "env": {
    "browser": true,
    "es6": true,
  },
  "parserOptions": {
    "sourceType": "module",
  },
  "extends": [
    "eslint:recommended",
    "google",
  ],
}
```

If you have more questions, please open them on the eslint repo, as this isn't really related to the Google JS style rules.
