### ISSUE TITLE
are tabs allowed?

### ISSUE THREAD

**Issue by reklatsmasters** [google/eslint-config-google#40]
[Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html#whitespace-characters) says:

>  **2.3.1 Whitespace characters**
> ...
> 2. Tab characters are not used for indentation.

but rule `indent` works incorrectly. As a result, I can write like  this:
![image](https://cloud.githubusercontent.com/assets/2255752/26098104/15986246-3a40-11e7-8558-7b3e627558c9.png)
And it will not cause an error.

**Comment by philipwalton** [comment]
Tabs are not allowed, but unfortunately the eslint options for the indent rule are not flexible enough to enforce all of Google's rules around indentation. You can see I have a TODO to fix this:
https://github.com/google/eslint-config-google/blob/master/index.js#L198-L199

That explains why there's not currently a warning for tabs (though you could easily add this yourself to your own config).

**Comment by philipwalton** [comment]
Actually, I think the answer to this question can be addressed by adding the `no-tabs` rule, which I think was mistakenly turned off.
