### ISSUE TITLE
More prominent note that this is for the ES6 style guide?

### ISSUE THREAD

**Issue by jyujin** [google/eslint-config-google#44]
Most searches for the Google JS style guide seem to point to this one: https://google.github.io/styleguide/javascriptguide.xml - but really this config is for the ES6 style guide here: https://google.github.io/styleguide/jsguide.html

It's not obvious from the readme which of the two style guides this config is for, and they disagree on some key issues (e.g. 'var' vs 'let' and 'const'). It'd be a good idea to clarify this.

I know there's a link at the top, but just rewording that to clarify it's the ES6 style guide would help since users who find the style guide first and then try to find a linter for it would otherwise be greatly surprised and are unlikely to check the link's target.

**Comment by philipwalton** [comment]
Good suggestion. Added!
