### ISSUE TITLE
[error] Definition for rule 'switch-colon-spacing' was not found

### ISSUE THREAD

**Issue by gastonche** [google/eslint-config-google#47]
I am using `eslint-config-google`, for my styles with eslint and I keep getting an error for all the files I am linting
` 1:1  error  Definition for rule 'switch-colon-spacing' was not found`

My .eslintrc this:
```
{
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module",
    "allowImportExportEverywhere": false,
    "codeFrame": false,
    "ecmaFeatures": {
      "jsx": true,
      "modules": true,
      "spread" : true,
      "restParams" : true
    }
  },
  "extends": ["eslint:recommended", "plugin:react/recommended", "google"],
  "globals": {
  	"require": true,
  	"module": true
  },
  "rules": {
    "strict": 1,
    "comma-spacing":1,
    "no-console":0,
    "indent": ["error", 2],
    "switch-colon-spacing": [
      "error", 
      {
        "after": true, 
        "before": false
      }
    ]
  },
  "env":{
    "es6": true,        // We are writing ES6 code
    "browser": true,    // for the browser
    "commonjs": true    // and use require() for stylesheets
  },
  "plugins": [
    "react"
  ]
}

```
I am unable to see what's wrong here

**Comment by philipwalton** [comment]
My guess is you're using a pre-4.0 version of eslint, which is when that rule was added. Without knowing more about your setup, it's impossible to say.

**Comment by spiffcp** [comment]
@gastonche 

If you have not found a solution for this I updated out .eslintrc.yml to the following as we are not really interested in using the rule in our lint configuration. See snippet below:

```yaml
extends: 
  - google
parser: "babel-eslint"
parserOptions:
  emcaVersion: 6
  sourceType: module
  emcaFeatures:
    modules: true
rules:
  switch-colon-spacing: 0
```

Options below:
Severity should be one of the following: 0 = off, 1 = warn, 2 = error.

**Comment by wraytw** [comment]
@philipwalton @gastonche I was working in a repo that had version 3 of eslint, upgrading to eslint 4 fixed the issue!
