### ISSUE TITLE
prefer-const should be enabled?

### ISSUE THREAD

**Issue by 43081j** [google/eslint-config-google#51]
It seems like it isn't enabled and eslint:recommended doesn't enable it either.

However, in the style guide [here](https://google.github.io/styleguide/jsguide.html#features-use-const-and-let):

> Declare all local variables with either const or let. Use const by default, unless a variable needs to be reassigned. The var keyword must not be used.

So surely this means it should be an error to use `let` for a variable which is not reassigned?

edit:

seems this is fixed by #49  if it gets merged.

**Comment by philipwalton** [comment]
Yeah, I've pinged the author of that PR to see if he'll sign the CLA. If not (or if he doesn't respond) I can add this myself.
