### ISSUE TITLE
Using const variable declaration shows as invalid

### ISSUE THREAD

**Issue by jvanalst** [google/eslint-config-google#53]
According to:
[5.1.1](https://google.github.io/styleguide/jsguide.html#features-use-const-and-let)
we should be using const by default.

But when I eslint against:
````
'use strict';
const stream = require('stream');
````

It outputs:
> /Users/vanalsti/Projects/examvis-eclass/examvis/eslint-test.js
>   2:1  error  Parsing error: The keyword 'const' is reserved
> 
> ✖ 1 problem (1 error, 0 warnings)

**Comment by Makki7** [comment]
eslint uses es5 syntax and you should let him know that you are using es6 syntax:
{
    "env": {
        "es6": true
    }
}

**Comment by iennae** [comment]
@jvanalst I'm going to go ahead and close this, as it looks like there have been a couple responses that answer the question. Please feel free to reopen if you have additional questions about resolving.
