### ISSUE TITLE
Does this config support for eslint 6.1.0 (lastest version)?

### ISSUE THREAD

**Issue by DemonCloud** [google/eslint-config-google#57]
I was update Eslint to 6.1.0 version
<img width="942" alt="Screen Shot 2019-07-31 at 4 28 48 PM" src="https://user-images.githubusercontent.com/7436361/62196552-d921d580-b3b0-11e9-9431-ce3cf38dd748.png">

my .eslintrc.js in $HOME dir, work fine at Eslint 5.0.0 version

```javascript
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
  },
  parser: 'babel-eslint',
  plugins: ['react'],
  extends: [
    'eslint:recommended',
    'google',
    'plugin:react/recommended',
    'prefer-object-spread',
  ],
  globals: {
    wx: null,
    App: null,
    Page: null,
    getApp: null,
    Component: null,
  },
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2017,
    sourceType: 'module',
  },
  rules: {
    'prefer-object-spread/prefer-object-spread': 2,
  }
};
```

**Comment by philipwalton** [comment]
I'm using this config with eslint 6.1.0 and it works for me. I suspect there's something else going on here that's causing issues fro you. I'm going to close this issue, but feel free to reply if you discover some other reason that it's not working properly.

**Comment by DemonCloud** [comment]
@philipwalton OK
