### ISSUE TITLE
Failing on TravisCI with missing module

### ISSUE THREAD

**Issue by jsonmaur** [google/eslint-config-google#8]
I'm getting `Error: Cannot find module 'eslint-config-xo'` when running a simple app built with Babel on Travis CI. Only fails on Node < 5.x. I can confirm `eslint-config-xo` was installed:
<img width="496" alt="screen shot 2016-02-25 at 3 38 38 pm" src="https://cloud.githubusercontent.com/assets/911274/13336906/e45a42e0-dbd5-11e5-8e8b-acc8b5bb008d.png">
Not sure if this is an issue with this repo, eslint, npm itself, or with travis. Just trying to narrow it down.

See this repo for example code:
https://github.com/jsonmaur/eslint-test

And the details on the failing builds:
https://travis-ci.org/jsonmaur/eslint-test

**Comment by jsonmaur** [comment]
It works if I manually install `eslint-config-xo`, but shouldn't it come with this module when I install it?

**Comment by sindresorhus** [comment]
Confirmed. I think this is a ESLint bug. According to http://eslint.org/blog/2016/02/eslint-v2.0.0-released#shareable-config-changes it should now be possible to [reference local npm dependencies](https://github.com/google/eslint-config-google/blob/7e75458986cf14982e2e3bd0e964030a8575ecb3/index.js#L19) in a sharable config, meaning it should be possible for a sharable config to extend another one. Mind opening an ESLint issue?

**Comment by jsonmaur** [comment]
It works if you change `extends: 'xo'` to `extends: 'eslint-config-google/node_modules/eslint-config-xo'`. But then the test no longer passes.

**Comment by sindresorhus** [comment]
Yes, but that will fail on npm@3 as it deduplicates dependencies.

**Comment by jsonmaur** [comment]
True. It seems that's the problem. Any npm version that doesn't dedupe throws the error.

**Comment by jsonmaur** [comment]
Fixed in ESLint master as of https://github.com/eslint/eslint/pull/5459. Tested it out, and all seems to be good. I think they have a scheduled release for this weekend, so I'll go ahead and close this issue.
