### ISSUE TITLE
Reflect latest eslint-config-xo

### ISSUE THREAD

**Issue by calvinkarundu** [google/eslint-config-google#9]
Extended xo config doesn't download the latest version of the main eslint-config-xo repo. Still includes deprecated rules in eslint ^2.0.0 Maybe it's not compatible? package.json reads `"eslint-config-xo": "^0.7.0"`

**Comment by benderTheCrime** [comment]
I'm not exactly sure if this is related because I don't fully understand the extent of the above comment, but the latest version of this package uses eslint-config-xo@^0.10.1, which does not cover eslint-config-xo@0.11.0.That version (eslint-config-xo@^0.10.1) does indeed have rules deprecated in eslint@^2.0.0, such as "no-empty-labels".

**Comment by calvinkarundu** [comment]
The inclusion of the deprecated rules is what I was pointing out. I'm forced to overwrite those rules after extending the google config so as to stop the linter from throwing errors. If you're aware though, that's fine; I just found it a bit redundant to disable deprecated rules when they shouldn't be there in the first place.

**Comment by benderTheCrime** [comment]
Ok, yeah I did the same thing. Nevertheless annoying to have to balloon out my own config file to account for deprecated rules.

:+1:

**Comment by addyosmani** [comment]
I agree we should probably clean this up. PR welcome if we need this sooner otherwise we'll try tackling this later on the week.

**Comment by sindresorhus** [comment]
All the [ESLint 2 changes](https://github.com/sindresorhus/eslint-config-xo/commit/56a33c64af556f7a24349c8e57ba10cb1cc85664) was part of eslint-config-xo@0.10.0 (which this package depends on), so I have no idea what's requested here.

**Comment by calvinkarundu** [comment]
My package.json read `"eslint-config-google": "^0.3.0"` and not `"^0.4.0"`. Bumped up the version number and everything looks good :+1:
